baseURL = 'http://oscar.cederberg.xyz/'
languageCode = 'en-us'
title = 'oscarcederberg'
theme= 'paige'
copyright= 'Oscar Cederberg'

[[languages.en.menu.main]]
identifier = "home"
name = "home"
url = "/"
weight = 10

[[languages.en.menu.main]]
identifier = "blog"
name = "blog"
url = "/posts/"
weight = 30

[permalinks]
blog = "/posts/:year/:month/:day/:title/"